### ISSUE TITLE
Module Setup Flow | AdSense: New user

### ISSUE THREAD

**Issue by bjackson27** [google/site-kit-wp#272]
See https://docs.google.com/drawings/d/1C9Y6ETjXgZOZVSNc4TDq-C7iHdVlZYCkOaoaUSpDtDw/edit

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* User clicks “connect service” for AdSense module
* Requested to grant AdSense API scopes → yes
* Check if they have an AdSense account → no AdSense account is detected 
Example API response for when there is no account for that user (reason: “NoAdSenseAccount”)
<img width="776" alt="Screenshot 2019-08-13 at 18 17 14" src="https://user-images.githubusercontent.com/13304791/63028497-3b99cc00-beaf-11e9-97bb-636796559429.png">

* Show “Create your AdSense account” screen (“Site Kit will place AdSense code on every page across your site.”)
* User clicks “Create AdSense account” button as part of the setup flow
* User is sent to AdSense account sign-up page to complete the necessary details for the account
* Plugin is constantly trying to detect an account (i.e. refreshing itself).

Scenario 1: The account is fully created (all details complete), but the API returns “Graylisted” status (accountStatus is ‘ads-display-pending’ and API response is “type: GRAYLISTED_PUBLISHER”):
* Plugin places AdSense code on all pages of the site (only test non-AMP for now)
* Show screen “We’re getting your site ready for ads” (future copy: Let’s get your site ready for ads) + link to AdSense account
* AdSense settings page should show the following status:
    * Account status: Pending
    * AdSense code: AdSense code is placed on your site

Scenario 2: The account is created, but the address is not added or phone not verified 
* Plugin places AdSense code on all pages of the site (only test non-AMP for now)
* Show screen “Your site isn’t ready for ads yet.” + link to AdSense FE
* User needs to go to AdSense FE and complete the missing details
* AdSense settings page should show the following status:
     * Account status: Action required
     * AdSense code: AdSense code is placed on your site
 
Scenario 3: The account is created, but the account is disapproved 
* Plugin places AdSense code on all pages of the site (only test non-AMP for now)
* Show screen “Your site isn’t ready for ads yet.” + link to AdSense FE
* User needs to go to AdSense FE and complete the missing details
* AdSense settings page should show the following status:
   * Account status: Action required
   * AdSense code: AdSense code is placed on your site

Scenario 4: The account is not yet created 
* Refresh the page to check for an account. No AdSense account is detected. Show “Create your AdSense account” screen (“Site Kit will place AdSense code on every page across your site.”)
* Settings page: show status "incomplete setup" + link to set up (which is the “Create your AdSense account” page).

## Implementation Brief

* n/a

## Changelog entry

* N/A

**Comment by aaemnnosttv** [comment]
@felixarntz @marrrmarrr 
> If the account is created, but the address/phone are not added OR if the account is disapproved

Should this be two separate scenarios to test?

**Comment by OisinOConnor** [comment]
> @felixarntz @marrrmarrr
> 
> > If the account is created, but the address/phone are not added OR if the account is disapproved
> 
> Should this be two separate scenarios to test?

Yes.
Disapproved should return an error for all API method calls.
Phone number/address verification, in some scenarios, will be available through the [alerts](https://developers.google.com/adsense/management/v1.4/reference/accounts/alerts/list). If the alerts aren't available (e.g. if account is pending) then apply the "graylisted" scenario.

**Comment by aaemnnosttv** [comment]
Moving this to criteria definition for splitting this into separate discrete scenarios:

1. The account is created, but the address/phone are not added
1. The account is created, but the account is disapproved

**Comment by marrrmarrr** [comment]
These tests conditions are accurate for the current flow in the plugin.

**Comment by aaemnnosttv** [comment]
Each scenario seems fairly straight forward to test, but we will need to collect a lot of requests to mock for each so this could be a bit time consuming. Estimating as a M for now.

**Comment by aaemnnosttv** [comment]
@felixarntz @marrrmarrr Regarding the AC for scenario 1 - when the account is in a graylisted status the Adsense script is not loaded on the frontend as it requires the client ID is set. Is this expected?

https://github.com/google/site-kit-wp/blob/84a2765a9f1da1d9f55d7c306ba79180e89e6b4e/assets/js/modules/adsense/util.js#L205-L219

**Comment by felixarntz** [comment]
As far as I recall, the `ads-display-pending` indicates that the account is pending, but the snippet should already be placed. But it's true, there's no way to print the script as long as there's no `clientID` stored.

Let's rely on what the code currently does for the initial e2e tests. They should then give us a solid base for comparing actual requirements with the current state, so we can then create follow-up issues where necessary.

**Comment by tofumatt** [comment]
These tests fail for me with a fresh checkout and `rm -rf node_modules && npm install && npm run env:reset && npm run test:e2e`. Here's the failures I'm getting:

```
 FAIL  tests/e2e/specs/modules/adsense/setup-new-user.test.js (109.12s)
  ● Console

    console.error tests/e2e/config/bootstrap.js:154
      Failed to load resource: the server responded with a status of 500 (Internal Server Error)

  ● setting up the AdSense module › displays “We’re getting your site ready for ads” when account
 is graylisted

    TimeoutError: Element .googlesitekit-setup-module__title (text: "/We’re getting your site ready for ads/i") not found

      waiting for function failed: timeout 500ms exceeded

  ● setting up the AdSense module › displays “We’re getting your site ready for ads” when the Adsense account is missing the address or phone not verified

    TimeoutError: Element .googlesitekit-setup-module__title (text: "/We’re getting your site ready for ads/i") not found

      waiting for function failed: timeout 500ms exceeded

  ● setting up the AdSense module › displays “Your site isn’t ready to show ads yet” when the users account is disapproved

    TimeoutError: Element .googlesitekit-setup-module__title (text: "/Your site isn’t ready to show ads yet/i") not found

      waiting for function failed: timeout 500ms exceeded

  ● setting up the AdSense module › displays “Create your AdSense account” when the user does not have an AdSense account

    TimeoutError: Element .googlesitekit-setup-module__title (text: "/Create your AdSense account/i") not found

      waiting for function failed: timeout 500ms exceeded
```

I'm using node `v10.16.0`, for what it's worth.

**Comment by aaemnnosttv** [comment]
@tofumatt it passes for me

```
npm run test:e2e -- tests/e2e/specs/modules/adsense/setup-new-user.test.js        

> googlesitekit@1.0.0-beta.1.0.6 test:e2e /Users/aaemnnosttv/10up/Sites/googlesitekit-test/wordpress/wp-content/plugins/google-site-kit
> WP_BASE_URL=http://localhost:9002 wp-scripts test-e2e --config=tests/e2e/jest.config.js "tests/e2e/specs/modules/adsense/setup-new-user.test.js"

  console.error tests/e2e/config/bootstrap.js:154
    Failed to load resource: the server responded with a status of 500 (Internal Server Error)

 PASS  tests/e2e/specs/modules/adsense/setup-new-user.test.js (62.906s)
  setting up the AdSense module
    ✓ displays “We’re getting your site ready for ads” when account is graylisted (12225ms)
    ✓ displays “We’re getting your site ready for ads” when the Adsense account is missing the address or phone not verified (11901ms)
    ✓ displays “Your site isn’t ready to show ads yet” when the users account is disapproved (11943ms)
    ✓ displays “Create your AdSense account” when the user does not have an AdSense account (13860ms)

Test Suites: 1 passed, 1 total
Tests:       4 passed, 4 total
Snapshots:   0 total
Time:        62.946s
Ran all test suites matching /tests\/e2e\/specs\/modules\/adsense\/setup-new-user.test.js/i.
```

Sounds like this might be a performance issue for your environment. Can you try [bumping up the default timeout](https://github.com/smooth-code/jest-puppeteer/blob/43eab46c8a674f7fe2945f4ac6a95b52609a9d24/packages/expect-puppeteer/README.md#configure-default-options) for Jest Puppeteer and try again?

**Comment by tofumatt** [comment]
Unfortunately increasing the timeout on the individual tests didn't help:

```
❯ npm run test:e2e -- tests/e2e/specs/modules/adsense/setup-new-user.test.js

> googlesitekit@1.0.0-beta.1.0.6 test:e2e /Users/matt/Projects/site-kit-wp
> WP_BASE_URL=http://localhost:9002 wp-scripts test-e2e --config=tests/e2e/jest.config.js "tests/e2e/specs/modules/adsense/setup-new-user.test.js"

  console.error tests/e2e/config/bootstrap.js:154
    Failed to load resource: the server responded with a status of 403 (Forbidden)

  console.error tests/e2e/config/bootstrap.js:154
    Failed to load resource: the server responded with a status of 403 (Forbidden)

  console.error tests/e2e/config/bootstrap.js:154
    Failed to load resource: the server responded with a status of 403 (Forbidden)

  console.error tests/e2e/config/bootstrap.js:154
    Failed to load resource: the server responded with a status of 403 (Forbidden)

 FAIL  tests/e2e/specs/modules/adsense/setup-new-user.test.js
  ● Test suite failed to run

    TimeoutError: waiting for selector "tr[data-slug="e2e-tests-reset-plugin"] .deactivate a" failed: timeout 30000ms exceeded

      at new WaitTask (../../node_modules/puppeteer/lib/DOMWorld.js:554:28)
      at DOMWorld._waitForSelectorOrXPath (../../node_modules/puppeteer/lib/DOMWorld.js:483:22)
      at DOMWorld.waitForSelector (../../node_modules/puppeteer/lib/DOMWorld.js:437:17)
      at Frame.waitForSelector (../../node_modules/puppeteer/lib/FrameManager.js:606:47)
      at Frame.<anonymous> (../../node_modules/puppeteer/lib/helper.js:109:23)
      at Page.waitForSelector (../../node_modules/puppeteer/lib/Page.js:1073:29)
      at waitForSelector (../../node_modules/@wordpress/e2e-test-utils/build/@wordpress/e2e-test-utils/src/activate-plugin.js:21:13)
      at tryCatch (../../node_modules/@wordpress/e2e-test-utils/node_modules/regenerator-runtime/runtime.js:45:40)
      at Generator.invoke [as _invoke] (../../node_modules/@wordpress/e2e-test-utils/node_modules/regenerator-runtime/runtime.js:271:22)
      at Generator.prototype.(anonymous function) [as next] (../../node_modules/@wordpress/e2e-test-utils/node_modules/regenerator-runtime/runtime.js:97:21)
        -- ASYNC --
      at Frame.<anonymous> (../../node_modules/puppeteer/lib/helper.js:108:27)
      at Page.waitForSelector (../../node_modules/puppeteer/lib/Page.js:1073:29)
      at waitForSelector (../../node_modules/@wordpress/e2e-test-utils/build/@wordpress/e2e-test-utils/src/activate-plugin.js:21:13)
      at tryCatch (../../node_modules/@wordpress/e2e-test-utils/node_modules/regenerator-runtime/runtime.js:45:40)
      at Generator.invoke [as _invoke] (../../node_modules/@wordpress/e2e-test-utils/node_modules/regenerator-runtime/runtime.js:271:22)
      at Generator.prototype.(anonymous function) [as next] (../../node_modules/@wordpress/e2e-test-utils/node_modules/regenerator-runtime/runtime.js:97:21)
      at asyncGeneratorStep (../../node_modules/@wordpress/e2e-test-utils/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
      at _next (../../node_modules/@wordpress/e2e-test-utils/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        421.555s
Ran all test suites matching /tests\/e2e\/specs\/modules\/adsense\/setup-new-user.test.js/i.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! googlesitekit@1.0.0-beta.1.0.6 test:e2e: `WP_BASE_URL=http://localhost:9002 wp-scripts test-e2e --config=tests/e2e/jest.config.js "tests/e2e/specs/modules/adsense/setup-new-user.test.js"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the googlesitekit@1.0.0-beta.1.0.6 test:e2e script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/matt/.npm/_logs/2019-09-23T14_28_26_973Z-debug.log
```

That was after changing the tests to have a much longer timeout (`20000ms`).

**Comment by tofumatt** [comment]
Even after rebuilding the package (I forgot, argh!) and experimenting with adding:

```php
if ( ! defined( 'GOOGLESITEKIT_PLUGIN_MAIN_FILE' ) ) {
	return;
}
```

to https://github.com/google/site-kit-wp/blob/780decdc6e8c4bbcd6b61717e0717decf854f57f/tests/e2e/plugins/reset.php#L18 I still see errors:

```
 FAIL  tests/e2e/specs/modules/adsense/setup-new-user.test.js (183.712s)
  ● Console

    console.error tests/e2e/config/bootstrap.js:154
      Failed to load resource: the server responded with a status of 500 (Internal Server Error)

  ● setting up the AdSense module › displays “We’re getting your site ready for ads” when account
 is graylisted

    Timeout - Async callback was not invoked within the 2000ms timeout specified by jest.setTimeout.

      93 |      } );
      94 | 
    > 95 |      it( 'displays “We’re getting your site ready for ads” when account is graylisted', async () => {
         |      ^
      96 |              datapointHandlers.accounts = ( request ) => {
      97 |                      request.respond( {
      98 |                              status: 200,

      at new Spec (../../node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
      at Suite.it (specs/modules/adsense/setup-new-user.test.js:95:2)

  ● setting up the AdSense module › displays “We’re getting your site ready for ads” when account is graylisted

    TimeoutError: Element .googlesitekit-setup-module__title (text: "/We’re getting your site ready for ads/i") not found

      waiting for function failed: timeout 500ms exceeded

  ● setting up the AdSense module › displays “We’re getting your site ready for ads” when account is graylisted

    TimeoutError: waiting for selector "input[type="checkbox"][value="google-site-kit/google-site-kit.php"]" failed: timeout 30000ms exceeded

      15 |      }
      16 | 
    > 17 |      await page.waitForSelector( 'input[type="checkbox"][value="google-site-kit/google-site-kit.php"]' );
         |                 ^
      18 |      const activePlugins = await page.$$eval( '.active[data-plugin]', ( rows ) => {
      19 |              return rows.map( ( row ) => row.dataset.plugin );
      20 |      } );

      at new WaitTask (../../node_modules/puppeteer/lib/DOMWorld.js:554:28)
      at DOMWorld._waitForSelectorOrXPath (../../node_modules/puppeteer/lib/DOMWorld.js:483:22)
      at DOMWorld.waitForSelector (../../node_modules/puppeteer/lib/DOMWorld.js:437:17)
      at Frame.waitForSelector (../../node_modules/puppeteer/lib/FrameManager.js:606:47)
      at Frame.<anonymous> (../../node_modules/puppeteer/lib/helper.js:109:23)
      at Page.waitForSelector (../../node_modules/puppeteer/lib/Page.js:1073:29)
      at waitForSelector (utils/deactivate-all-other-plugins.js:17:13)
      at tryCatch (../../node_modules/regenerator-runtime/runtime.js:62:40)
      at Generator.invoke [as _invoke] (../../node_modules/regenerator-runtime/runtime.js:288:22)
      at Generator.prototype.(anonymous function) [as next] (../../node_modules/regenerator-runtime/runtime.js:114:21)
        -- ASYNC --
      at Frame.<anonymous> (../../node_modules/puppeteer/lib/helper.js:108:27)
      at Page.waitForSelector (../../node_modules/puppeteer/lib/Page.js:1073:29)
      at waitForSelector (utils/deactivate-all-other-plugins.js:17:13)
      at tryCatch (../../node_modules/regenerator-runtime/runtime.js:62:40)
      at Generator.invoke [as _invoke] (../../node_modules/regenerator-runtime/runtime.js:288:22)
      at Generator.prototype.(anonymous function) [as next] (../../node_modules/regenerator-runtime/runtime.js:114:21)
      at asyncGeneratorStep (../../node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
      at _next (../../node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)

  ● setting up the AdSense module › displays “We’re getting your site ready for ads” when the Adsense account is missing the address or phone not verified

    Timeout - Async callback was not invoked within the 2000ms timeout specified by jest.setTimeout.

      144 |     }, 2000 );
      145 | 
    > 146 |     it( 'displays “We’re getting your site ready for ads” when the Adsense account is missing the address or phone not verified', async () => {
          |     ^
      147 |             datapointHandlers.accounts = ( request ) => {
      148 |                     request.respond( {
      149 |                             status: 200,

      at new Spec (../../node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
      at Suite.it (specs/modules/adsense/setup-new-user.test.js:146:2)

  ● setting up the AdSense module › displays “We’re getting your site ready for ads” when the Adsense account is missing the address or phone not verified

    TimeoutError: waiting for selector "input[type="checkbox"][value="google-site-kit/google-site-kit.php"]" failed: timeout 30000ms exceeded

      15 |      }
      16 | 
    > 17 |      await page.waitForSelector( 'input[type="checkbox"][value="google-site-kit/google-site-kit.php"]' );
         |                 ^
      18 |      const activePlugins = await page.$$eval( '.active[data-plugin]', ( rows ) => {
      19 |              return rows.map( ( row ) => row.dataset.plugin );
      20 |      } );

      at new WaitTask (../../node_modules/puppeteer/lib/DOMWorld.js:554:28)
      at DOMWorld._waitForSelectorOrXPath (../../node_modules/puppeteer/lib/DOMWorld.js:483:22)
      at DOMWorld.waitForSelector (../../node_modules/puppeteer/lib/DOMWorld.js:437:17)
      at Frame.waitForSelector (../../node_modules/puppeteer/lib/FrameManager.js:606:47)
      at Frame.<anonymous> (../../node_modules/puppeteer/lib/helper.js:109:23)
      at Page.waitForSelector (../../node_modules/puppeteer/lib/Page.js:1073:29)
      at waitForSelector (utils/deactivate-all-other-plugins.js:17:13)
      at tryCatch (../../node_modules/regenerator-runtime/runtime.js:62:40)
      at Generator.invoke [as _invoke] (../../node_modules/regenerator-runtime/runtime.js:288:22)
      at Generator.prototype.(anonymous function) [as next] (../../node_modules/regenerator-runtime/runtime.js:114:21)
        -- ASYNC --
      at Frame.<anonymous> (../../node_modules/puppeteer/lib/helper.js:108:27)
      at Page.waitForSelector (../../node_modules/puppeteer/lib/Page.js:1073:29)
      at waitForSelector (utils/deactivate-all-other-plugins.js:17:13)
      at tryCatch (../../node_modules/regenerator-runtime/runtime.js:62:40)
      at Generator.invoke [as _invoke] (../../node_modules/regenerator-runtime/runtime.js:288:22)
      at Generator.prototype.(anonymous function) [as next] (../../node_modules/regenerator-runtime/runtime.js:114:21)
      at asyncGeneratorStep (../../node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
      at _next (../../node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)

  ● setting up the AdSense module › displays “Your site isn’t ready to show ads yet” when the users account is disapproved

    TimeoutError: waiting for selector ".googlesitekit-settings-connect-module--adsense" failed: timeout 30000ms exceeded

      21 |      await page.waitForSelector( '.mdc-tab-bar' );
      22 |      await expect( page ).toClick( '.mdc-tab', { text: /connect more services/i } );
    > 23 |      await page.waitForSelector( '.googlesitekit-settings-connect-module--adsense' );
         |                 ^
      24 | 
      25 |      await Promise.all( [
      26 |              expect( page ).toClick( '.googlesitekit-cta-link', { text: /set up adsense/i } ),

      at new WaitTask (../../node_modules/puppeteer/lib/DOMWorld.js:554:28)
      at DOMWorld._waitForSelectorOrXPath (../../node_modules/puppeteer/lib/DOMWorld.js:483:22)
      at DOMWorld.waitForSelector (../../node_modules/puppeteer/lib/DOMWorld.js:437:17)
      at Frame.waitForSelector (../../node_modules/puppeteer/lib/FrameManager.js:606:47)
      at Frame.<anonymous> (../../node_modules/puppeteer/lib/helper.js:109:23)
      at Page.waitForSelector (../../node_modules/puppeteer/lib/Page.js:1073:29)
      at waitForSelector (specs/modules/adsense/setup-new-user.test.js:23:13)
      at tryCatch (../../node_modules/regenerator-runtime/runtime.js:62:40)
      at Generator.invoke [as _invoke] (../../node_modules/regenerator-runtime/runtime.js:288:22)
      at Generator.prototype.(anonymous function) [as next] (../../node_modules/regenerator-runtime/runtime.js:114:21)
        -- ASYNC --
      at Frame.<anonymous> (../../node_modules/puppeteer/lib/helper.js:108:27)
      at Page.waitForSelector (../../node_modules/puppeteer/lib/Page.js:1073:29)
      at waitForSelector (specs/modules/adsense/setup-new-user.test.js:23:13)
      at tryCatch (../../node_modules/regenerator-runtime/runtime.js:62:40)
      at Generator.invoke [as _invoke] (../../node_modules/regenerator-runtime/runtime.js:288:22)
      at Generator.prototype.(anonymous function) [as next] (../../node_modules/regenerator-runtime/runtime.js:114:21)
      at asyncGeneratorStep (../../node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
      at _next (../../node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)

  ● setting up the AdSense module › displays “Your site isn’t ready to show ads yet” when the users account is disapproved

    Timeout - Async callback was not invoked within the 20000ms timeout specified by jest.setTimeout.

      202 |     }, 2000 );
      203 | 
    > 204 |     it( 'displays “Your site isn’t ready to show ads yet” when the users account is disapproved', async () => {
          |     ^
      205 |             datapointHandlers.accounts = ( request ) => {
      206 |                     request.respond( {
      207 |                             status: 200,

      at new Spec (../../node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
      at Suite.it (specs/modules/adsense/setup-new-user.test.js:204:2)

  ● setting up the AdSense module › displays “Your site isn’t ready to show ads yet” when the users account is disapproved

    TimeoutError: waiting for selector ".googlesitekit-settings-connect-module--adsense" failed: timeout 30000ms exceeded

      21 |      await page.waitForSelector( '.mdc-tab-bar' );
      22 |      await expect( page ).toClick( '.mdc-tab', { text: /connect more services/i } );
    > 23 |      await page.waitForSelector( '.googlesitekit-settings-connect-module--adsense' );
         |                 ^
      24 | 
      25 |      await Promise.all( [
      26 |              expect( page ).toClick( '.googlesitekit-cta-link', { text: /set up adsense/i } ),

      at new WaitTask (../../node_modules/puppeteer/lib/DOMWorld.js:554:28)
      at DOMWorld._waitForSelectorOrXPath (../../node_modules/puppeteer/lib/DOMWorld.js:483:22)
      at DOMWorld.waitForSelector (../../node_modules/puppeteer/lib/DOMWorld.js:437:17)
      at Frame.waitForSelector (../../node_modules/puppeteer/lib/FrameManager.js:606:47)
      at Frame.<anonymous> (../../node_modules/puppeteer/lib/helper.js:109:23)
      at Page.waitForSelector (../../node_modules/puppeteer/lib/Page.js:1073:29)
      at waitForSelector (specs/modules/adsense/setup-new-user.test.js:23:13)
      at tryCatch (../../node_modules/regenerator-runtime/runtime.js:62:40)
      at Generator.invoke [as _invoke] (../../node_modules/regenerator-runtime/runtime.js:288:22)
      at Generator.prototype.(anonymous function) [as next] (../../node_modules/regenerator-runtime/runtime.js:114:21)
        -- ASYNC --
      at Frame.<anonymous> (../../node_modules/puppeteer/lib/helper.js:108:27)
      at Page.waitForSelector (../../node_modules/puppeteer/lib/Page.js:1073:29)
      at waitForSelector (specs/modules/adsense/setup-new-user.test.js:23:13)
      at tryCatch (../../node_modules/regenerator-runtime/runtime.js:62:40)
      at Generator.invoke [as _invoke] (../../node_modules/regenerator-runtime/runtime.js:288:22)
      at Generator.prototype.(anonymous function) [as next] (../../node_modules/regenerator-runtime/runtime.js:114:21)
      at asyncGeneratorStep (../../node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
      at _next (../../node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)

  ● setting up the AdSense module › displays “Create your AdSense account” when the user does not have an AdSense account

    TimeoutError: Element .googlesitekit-setup-module__title (text: "/Create your AdSense account/i") not found

      waiting for function failed: timeout 500ms exceeded
```

@aaemnnosttv pointed me to an odd "reset" bug that the above fixed, but I'm still seeing an error. I'm pretty baffled here, I might try entirely removing my docker containers and restoring them—maybe my test environment is in a strange state. 🤷‍♀

**Comment by tofumatt** [comment]
I'm unable to QA this as my local test environment is inexplicably broken. I'm really unsure how to proceed, but it'd be good to know if others are experiencing this as well.

**Comment by tofumatt** [comment]
The E2E tests have been fixed and now this runs gloriously!

<img width="702" alt="Screenshot 2019-09-25 18 09 13" src="https://user-images.githubusercontent.com/90871/65624375-a3205c80-dfc1-11e9-8cc8-eab7597f422c.png">
<img width="707" alt="Screenshot 2019-09-25 18 05 52" src="https://user-images.githubusercontent.com/90871/65624377-a3205c80-dfc1-11e9-83cb-50c171997b59.png">
