### ISSUE TITLE
An error occurred while running ‘mapSelect’: Cannot read properties of null (reading ‘getWidgetState’)

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#4181]
## Bug Description

One user in the support forums is encounter the below in all their Site Kit dashboard tabs:

```
An error occurred while running ‘mapSelect’: Cannot read properties of null (reading ‘getWidgetState’)
The error may be correlated with this previous error:
TypeError: Cannot read properties of null (reading ‘getWidgetState’)
```

The plugin was working previously as expected. Further details below:

<details>
<summary>
Console Errors:
</summary>

```
GET https://www.tekstmeester.nl/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-widgets.dba9c49d296aa3e4cfd0.js net::ERR_ABORTED 403
jquery-migrate.min.js?ver=3.3.2:2 JQMIGRATE: Migrate is installed, version 3.3.2
admin.php:497 GET https://www.tekstmeester.nl/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-widgets.dba9c49d296aa3e4cfd0.js net::ERR_ABORTED 403
googlesitekit-modules-search-console.226957e30a2d0ea4d15b.js:40 Uncaught TypeError: Cannot read properties of undefined (reading 'registerWidget')
    at Module.992 (googlesitekit-modules-search-console.226957e30a2d0ea4d15b.js:40)
    at __webpack_require__ (runtime.15f5207b7118bf7aa6eb.js:1)
    at _ (runtime.15f5207b7118bf7aa6eb.js:1)
    at Array.r [as push] (runtime.15f5207b7118bf7aa6eb.js:1)
    at googlesitekit-modules-search-console.226957e30a2d0ea4d15b.js:1
992 @ googlesitekit-modules-search-console.226957e30a2d0ea4d15b.js:40
__webpack_require__ @ runtime.15f5207b7118bf7aa6eb.js:1
_ @ runtime.15f5207b7118bf7aa6eb.js:1
r @ runtime.15f5207b7118bf7aa6eb.js:1
(anonymous) @ googlesitekit-modules-search-console.226957e30a2d0ea4d15b.js:1
googlesitekit-modules-adsense.49307d144d570ef74bf9.js:74 Uncaught TypeError: Cannot read properties of undefined (reading 'registerWidget')
    at Module.985 (googlesitekit-modules-adsense.49307d144d570ef74bf9.js:74)
    at __webpack_require__ (runtime.15f5207b7118bf7aa6eb.js:1)
    at _ (runtime.15f5207b7118bf7aa6eb.js:1)
    at Array.r [as push] (runtime.15f5207b7118bf7aa6eb.js:1)
    at googlesitekit-modules-adsense.49307d144d570ef74bf9.js:1
985 @ googlesitekit-modules-adsense.49307d144d570ef74bf9.js:74
__webpack_require__ @ runtime.15f5207b7118bf7aa6eb.js:1
_ @ runtime.15f5207b7118bf7aa6eb.js:1
r @ runtime.15f5207b7118bf7aa6eb.js:1
(anonymous) @ googlesitekit-modules-adsense.49307d144d570ef74bf9.js:1
googlesitekit-modules-analytics.302c580cf060fb7bd10d.js:88 Uncaught TypeError: Cannot read properties of undefined (reading 'registerWidget')
    at Module.986 (googlesitekit-modules-analytics.302c580cf060fb7bd10d.js:88)
    at __webpack_require__ (runtime.15f5207b7118bf7aa6eb.js:1)
    at _ (runtime.15f5207b7118bf7aa6eb.js:1)
    at Array.r [as push] (runtime.15f5207b7118bf7aa6eb.js:1)
    at googlesitekit-modules-analytics.302c580cf060fb7bd10d.js:1
986 @ googlesitekit-modules-analytics.302c580cf060fb7bd10d.js:88
__webpack_require__ @ runtime.15f5207b7118bf7aa6eb.js:1
_ @ runtime.15f5207b7118bf7aa6eb.js:1
r @ runtime.15f5207b7118bf7aa6eb.js:1
(anonymous) @ googlesitekit-modules-analytics.302c580cf060fb7bd10d.js:1
googlesitekit-modules-pagespeed-insights.d59daafdd7e30e0c9019.js:24 Uncaught TypeError: Cannot read properties of undefined (reading 'registerWidget')
    at Module.994 (googlesitekit-modules-pagespeed-insights.d59daafdd7e30e0c9019.js:24)
    at __webpack_require__ (runtime.15f5207b7118bf7aa6eb.js:1)
    at _ (runtime.15f5207b7118bf7aa6eb.js:1)
    at Array.r [as push] (runtime.15f5207b7118bf7aa6eb.js:1)
    at googlesitekit-modules-pagespeed-insights.d59daafdd7e30e0c9019.js:1
994 @ googlesitekit-modules-pagespeed-insights.d59daafdd7e30e0c9019.js:24
__webpack_require__ @ runtime.15f5207b7118bf7aa6eb.js:1
_ @ runtime.15f5207b7118bf7aa6eb.js:1
r @ runtime.15f5207b7118bf7aa6eb.js:1
(anonymous) @ googlesitekit-modules-pagespeed-insights.d59daafdd7e30e0c9019.js:1
googlesitekit-vendor.09a03314e181c3acf88e.js:1 Error: An error occurred while running 'mapSelect': Cannot read properties of null (reading 'getWidgetAreas')
The error may be correlated with this previous error:
TypeError: Cannot read properties of null (reading 'getWidgetAreas')
    at Object.current (https://www.tekstmeester.nl/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-dashboard.0d9affe9cb1fddce810a.js:39:708)
    at e (https://www.tekstmeester.nl/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor.09a03314e181c3acf88e.js:1:235101)
    at https://www.tekstmeester.nl/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor.09a03314e181c3acf88e.js:1:235210
    at Ui (https://www.tekstmeester.nl/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor.09a03314e181c3acf88e.js:1:813979)
    at ya (https://www.tekstmeester.nl/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor.09a03314e181c3acf88e.js:1:836902)
    at t.unstable_runWithPriority (https://www.tekstmeester.nl/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor.09a03314e181c3acf88e.js:1:856525)
    at Mr (https://www.tekstmeester.nl/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor.09a03314e181c3acf88e.js:1:781631)
    at Yj (https://www.tekstmeester.nl/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor.09a03314e181c3acf88e.js:1:833331)
    at Lj (https://www.tekstmeester.nl/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor.09a03314e181c3acf88e.js:1:823691)
    at https://www.tekstmeester.nl/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor.09a03314e181c3acf88e.js:1:781922

Original stack trace:
    at Ke (https://www.tekstmeester.nl/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor.09a03314e181c3acf88e.js:1:234910)
    at WidgetContextRenderer (https://www.tekstmeester.nl/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-dashboard.0d9affe9cb1fddce810a.js:39:678)
    at Ih (https://www.tekstmeester.nl/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor.09a03314e181c3acf88e.js:1:795526)
    at ai (https://www.tekstmeester.nl/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor.09a03314e181c3acf88e.js:1:803748)
    at wi (https://www.tekstmeester.nl/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor.09a03314e181c3acf88e.js:1:841793)
    at ga (https://www.tekstmeester.nl/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor.09a03314e181c3acf88e.js:1:826221)
    at Zj (https://www.tekstmeester.nl/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor.09a03314e181c3acf88e.js:1:826146)
    at Lj (https://www.tekstmeester.nl/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor.09a03314e181c3acf88e.js:1:823492)
    at https://www.tekstmeester.nl/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor.09a03314e181c3acf88e.js:1:781922
    at t.unstable_runWithPriority (https://www.tekstmeester.nl/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor.09a03314e181c3acf88e.js:1:856525)
Pi @ googlesitekit-vendor.09a03314e181c3acf88e.js:1
i.componentDidCatch.n.callback @ googlesitekit-vendor.09a03314e181c3acf88e.js:1
Lg @ googlesitekit-vendor.09a03314e181c3acf88e.js:1
Kg @ googlesitekit-vendor.09a03314e181c3acf88e.js:1
ya @ googlesitekit-vendor.09a03314e181c3acf88e.js:1
t.unstable_runWithPriority @ googlesitekit-vendor.09a03314e181c3acf88e.js:1
Mr @ googlesitekit-vendor.09a03314e181c3acf88e.js:1
Yj @ googlesitekit-vendor.09a03314e181c3acf88e.js:1
Lj @ googlesitekit-vendor.09a03314e181c3acf88e.js:1
(anonymous) @ googlesitekit-vendor.09a03314e181c3acf88e.js:1
t.unstable_runWithPriority @ googlesitekit-vendor.09a03314e181c3acf88e.js:1
Mr @ googlesitekit-vendor.09a03314e181c3acf88e.js:1
Br @ googlesitekit-vendor.09a03314e181c3acf88e.js:1
zr @ googlesitekit-vendor.09a03314e181c3acf88e.js:1
Rg @ googlesitekit-vendor.09a03314e181c3acf88e.js:1
Sh @ googlesitekit-vendor.09a03314e181c3acf88e.js:1
(anonymous) @ googlesitekit-dashboard.0d9affe9cb1fddce810a.js:21
s @ googlesitekit-vendor.09a03314e181c3acf88e.js:1
(anonymous) @ googlesitekit-vendor.09a03314e181c3acf88e.js:1
forEach.e.<computed> @ googlesitekit-vendor.09a03314e181c3acf88e.js:1
n @ googlesitekit-vendor.09a03314e181c3acf88e.js:1
_next @ googlesitekit-vendor.09a03314e181c3acf88e.js:1
Promise.then (async)
n @ googlesitekit-vendor.09a03314e181c3acf88e.js:1
_next @ googlesitekit-vendor.09a03314e181c3acf88e.js:1
(anonymous) @ googlesitekit-vendor.09a03314e181c3acf88e.js:1
(anonymous) @ googlesitekit-vendor.09a03314e181c3acf88e.js:1
(anonymous) @ googlesitekit-dashboard.0d9affe9cb1fddce810a.js:21
Ui @ googlesitekit-vendor.09a03314e181c3acf88e.js:1
_a @ googlesitekit-vendor.09a03314e181c3acf88e.js:1
t.unstable_runWithPriority @ googlesitekit-vendor.09a03314e181c3acf88e.js:1
Mr @ googlesitekit-vendor.09a03314e181c3acf88e.js:1
Sj @ googlesitekit-vendor.09a03314e181c3acf88e.js:1
(anonymous) @ googlesitekit-vendor.09a03314e181c3acf88e.js:1
z @ googlesitekit-vendor.09a03314e181c3acf88e.js:1
j.port1.onmessage @ googlesitekit-vendor.09a03314e181c3acf88e.js:1
googlesitekit-dashboard.0d9affe9cb1fddce810a.js:21 Caught an error: Error: An error occurred while running 'mapSelect': Cannot read properties of null (reading 'getWidgetAreas')
The error may be correlated with this previous error:
TypeError: Cannot read properties of null (reading 'getWidgetAreas')
    at Object.current (https://www.tekstmeester.nl/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-dashboard.0d9affe9cb1fddce810a.js:39:708)
    at e (https://www.tekstmeester.nl/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor.09a03314e181c3acf88e.js:1:235101)
    at https://www.tekstmeester.nl/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor.09a03314e181c3acf88e.js:1:235210
    at Ui (https://www.tekstmeester.nl/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor.09a03314e181c3acf88e.js:1:813979)
    at ya (https://www.tekstmeester.nl/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor.09a03314e181c3acf88e.js:1:836902)
    at t.unstable_runWithPriority (https://www.tekstmeester.nl/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor.09a03314e181c3acf88e.js:1:856525)
    at Mr (https://www.tekstmeester.nl/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor.09a03314e181c3acf88e.js:1:781631)
    at Yj (https://www.tekstmeester.nl/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor.09a03314e181c3acf88e.js:1:833331)
    at Lj (https://www.tekstmeester.nl/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor.09a03314e181c3acf88e.js:1:823691)
    at https://www.tekstmeester.nl/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor.09a03314e181c3acf88e.js:1:781922

Original stack trace:
    at Ke (https://www.tekstmeester.nl/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor.09a03314e181c3acf88e.js:1:234910)
    at WidgetContextRenderer (https://www.tekstmeester.nl/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-dashboard.0d9affe9cb1fddce810a.js:39:678)
    at Ih (https://www.tekstmeester.nl/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor.09a03314e181c3acf88e.js:1:795526)
    at ai (https://www.tekstmeester.nl/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor.09a03314e181c3acf88e.js:1:803748)
    at wi (https://www.tekstmeester.nl/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor.09a03314e181c3acf88e.js:1:841793)
    at ga (https://www.tekstmeester.nl/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor.09a03314e181c3acf88e.js:1:826221)
    at Zj (https://www.tekstmeester.nl/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor.09a03314e181c3acf88e.js:1:826146)
    at Lj (https://www.tekstmeester.nl/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor.09a03314e181c3acf88e.js:1:823492)
    at https://www.tekstmeester.nl/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor.09a03314e181c3acf88e.js:1:781922
    at t.unstable_runWithPriority (https://www.tekstmeester.nl/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor.09a03314e181c3acf88e.js:1:856525) {componentStack: '\n    in WidgetContextRenderer\n    in DashboardApp\n… RestoreSnapshots\n    in ErrorHandler\n    in Root'}
```
</details>

## Additional Context

 - [Support topic](https://wordpress.org/support/topic/site-kit-not-working-anymore/#post-14935824)
 - [Site Health information provided](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/edit#response=ACYDBNidE7ipwHDe26ueRJMI-LCyVAgWUasXLkTL3Jf3s4ykfWGKpR9LG-dm8Rh5MskYzzE)
 - Site Kit 1.42.0
 - The first such occurance
 - Unlikely a plugin or theme conflict - test with only Site Kit active and a core theme via the Health Check & Troubleshooting plugin

## Insights & Troubleshooting Checks performed 

- [x] Health Check & Troubleshooting plugin check
- [x] Front end check (mixed content, minified content, combined JS)
- [x] Incognito mode 
- [x] Checked users Site Health info - there is a Thrive builder and theme active, which did cause issues on the front end [previously](https://wordpress.org/support/topic/google-site-kit-not-triggering-on-website/). This doesn't seem to be the cause given the users check with the Health Check plugin
- [x] Uninstalled and reinstalled plugin
- [ ] User confirmed no "Critical errors" in their Site Health status
- [ ] Temporary disabled WAF rules at host level - including ModSecurity
- [ ] Checked site setup and dashboard from another WordPress site on the same hosting platform
- [ ] Reset Site Kit 
- [ ] Disconnected from Site Kit
- [ ] Checked does the same occur from another admin users account
- [ ] Checked setup / viewing dashboards from another WordPress administrator account
- [ ] Reviewed error logs 
- [ ] Reviewed XHR requests 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
@jamesozzie interesting that you were able to reproduce it as well. It's the same 403 error on the JS asset file. The restriction could be applied outside of htaccess as well (e.g. WAF at CDN).

You can see the file is blocked when requesting directly:

https://wexico-w065c2.preview.wpmanaged.nl/james/wordpress/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-widgets.dba9c49d296aa3e4cfd0.js

Compared to this one which works

https://wexico-w065c2.preview.wpmanaged.nl/james/wordpress/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-dashboard.0d9affe9cb1fddce810a.js

**Comment by aaemnnosttv** [comment]
@jamesozzie I'm going to move this forward as we were able to identify the cause which is rather simple to prevent from happening again in the future.

**Comment by jamesozzie** [comment]
In addition to the upcoming plugin changes the hosting company used by the original reporter have made changes to their firewall. Providing users have their WordPress installs contained within a standard directory folder (public_html) users are now unlikely to encounter this error. 

The user did also confirm these changes resulted in Site Kit working as expected. On my test site I have my WordPress install contained within a james/wordpress/ path, with the error remaining. To be checked once the plugin changes are complete.

**Comment by wpdarren** [comment]
@aaemnnosttv I am wondering if this is a `QA:Eng` ticket.  If you do not feel it is, please could you give me additional details because the QAB whooshed over my head 👍

**Comment by cole10up** [comment]
### **QA Update: ⚠️**

**Ran the following:**

Coles-MacBook-Air:google-site-kit cole$ npm run build:production

> googlesitekit@ prebuild:production /Users/cole/Local Sites/googlekitlocal10uplabscom/app/public/wp-content/plugins/google-site-kit
> npm run remove-dist


> googlesitekit@ remove-dist /Users/cole/Local Sites/googlekitlocal10uplabscom/app/public/wp-content/plugins/google-site-kit
> rimraf ./dist


> googlesitekit@ build:production /Users/cole/Local Sites/googlekitlocal10uplabscom/app/public/wp-content/plugins/google-site-kit
> webpack --mode=production


✔ Basic Modules
  Compiled successfully in 14.99s

✖ Module Entry Points
  Compiled with some errors in 37.46s

● Plugin CSS █████████████████████████ building (50%) 4/5 modules 1 active
 css-loader › postcss-loader › sass-loader › assets/sass/admin.scss


✔ Basic Modules
  Compiled successfully in 14.99s

✖ Module Entry Points
  Compiled with some errors in 37.46s

✔ Plugin CSS
  Compiled successfully in 42.17s

Child

    ERROR in Failed to load plugin 'sitekit' declared in '.eslintrc.json': Unexpected token .
    Referenced from: /Users/cole/Local Sites/googlekitlocal10uplabscom/app/public/wp-content/plugins/google-site-kit/.eslintrc.json
Child

    WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
    This can impact web performance.
    Assets:
      /assets/css/googlesitekit-admin-css-fd3090e22c3c1a30e743.css (361 KiB)

    WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
    Entrypoints:
      googlesitekit-admin-css (362 KiB)
          /assets/css/googlesitekit-admin-css-fd3090e22c3c1a30e743.css
          googlesitekit-admin-css.js


    WARNING in webpack performance recommendations:
    You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
    For more info visit https://webpack.js.org/guides/code-splitting/
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! googlesitekit@ build:production: `webpack --mode=production`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the googlesitekit@ build:production script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/cole/.npm/_logs/2021-10-17T20_33_34_149Z-debug.log
Coles-MacBook-Air:google-site-kit cole$

Checked a file in /dist/js

Ran a search on **hash** which didn't turn up any items. 
![image](https://user-images.githubusercontent.com/57115907/137644171-0023ce2a-1106-4803-a3c0-e36d8f55443e.png)

I also examined the file which didn't show the expected **-[hash].(ext)**

![image](https://user-images.githubusercontent.com/57115907/137644224-d2209df2-599d-4025-863e-9d0734237bac.png)

I think we need to either QA:Eng this ticket or adjust the QAB as I'm unable to confirm this ticket.
