### ISSUE TITLE
PHP tests broken on PHP 8 with WP latest

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#4729]
## Bug Description

https://github.com/google/site-kit-wp/runs/4963741256?check_suite_focus=true#step:11:11

```
> phpunit
PHP Warning:  require_once(/tmp/wordpress-tests-lib/includes/phpunit7/MockObject/Builder/NamespaceMatch.php): Failed to open stream: No such file or directory in /home/runner/work/site-kit-wp/site-kit-wp/tests/phpunit/bootstrap.php on line 56
PHP Fatal error:  Uncaught Error: Failed opening required '/tmp/wordpress-tests-lib/includes/phpunit7/MockObject/Builder/NamespaceMatch.php' (include_path='.:/usr/share/php') in /home/runner/work/site-kit-wp/site-kit-wp/tests/phpunit/bootstrap.php:56
Stack trace:
#0 /home/runner/work/site-kit-wp/site-kit-wp/vendor/phpunit/phpunit/src/Util/FileLoader.php(57): include_once()
#1 /home/runner/work/site-kit-wp/site-kit-wp/vendor/phpunit/phpunit/src/Util/FileLoader.php(45): PHPUnit\Util\FileLoader::load()
#2 /home/runner/work/site-kit-wp/site-kit-wp/vendor/phpunit/phpunit/src/TextUI/Command.php(1058): PHPUnit\Util\FileLoader::checkAndLoad()
#3 /home/runner/work/site-kit-wp/site-kit-wp/vendor/phpunit/phpunit/src/TextUI/Command.php(863): PHPUnit\TextUI\Command->handleBootstrap()
#4 /home/runner/work/site-kit-wp/site-kit-wp/vendor/phpunit/phpunit/src/TextUI/Command.php(173): PHPUnit\TextUI\Command->handleArguments()
#5 /home/runner/work/site-kit-wp/site-kit-wp/vendor/phpunit/phpunit/src/TextUI/Command.php(162): PHPUnit\TextUI\Command->run()
#6 /home/runner/work/site-kit-wp/site-kit-wp/vendor/phpunit/phpunit/phpunit(61): PHPUnit\TextUI\Command::main()
#7 /home/runner/work/site-kit-wp/site-kit-wp/vendor/bin/phpunit(120): include('...')
#8 {main}
  thrown in /home/runner/work/site-kit-wp/site-kit-wp/tests/phpunit/bootstrap.php on line 56

Warning: require_once(/tmp/wordpress-tests-lib/includes/phpunit7/MockObject/Builder/NamespaceMatch.php): Failed to open stream: No such file or directory in /home/runner/work/site-kit-wp/site-kit-wp/tests/phpunit/bootstrap.php on line 56

Fatal error: Uncaught Error: Failed opening required '/tmp/wordpress-tests-lib/includes/phpunit7/MockObject/Builder/NamespaceMatch.php' (include_path='.:/usr/share/php') in /home/runner/work/site-kit-wp/site-kit-wp/tests/phpunit/bootstrap.php:56
```

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* PHP tests should continue to run and pass on PHP 8

## Implementation Brief

* Update the version constraint in `composer.json` for PHPUnit to allow PHPUnit 8 (we cannot yet upgrade to v9 even though it's supported by the polyfills package due to deprecated use that needs to be addressed)
* Remove old compatibility code loaded in the PHPUnit bootstrap which no longer exists in the latest version
* Update PHPUnit lifecycle methods (setup/teardown) to use snake case variants for compatibility across PHPUnit versions (see https://github.com/Yoast/PHPUnit-Polyfills#option-1-yoastphpunitpolyfillstestcasestestcase)
* Finish and merge https://github.com/google/site-kit-wp/pull/4730

### Test Coverage

* No change

## QA Brief

* This is verifiable by observing the passing tests (and output) of the PHP Test jobs in GitHub actions
* No further QA is needed

## Changelog entry

* N/A

**Comment by eugene-manuilov** [comment]
IB :heavy_check_mark:
