### ISSUE TITLE
Errors showing when we set up site kit on site without SSL.

### ISSUE THREAD

**Issue by mohitwp** [google/site-kit-wp#5991]
## Bug Description

When we set up site kit on site without SSL then it shows error if  TwG module is active and user connects analytics module.

```An error occurred while running 'mapSelect': Cannot read properties of null (reading 'getPublicationID')
The error may be correlated with this previous error:
TypeError: Cannot read properties of null (reading 'getPublicationID')
    at Object.current (http://hivevine.com/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-dashboard-b54aae02bf412137dae6.js:68:14179)
    at e (http://hivevine.com/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor-26b0b943bef4e536710f.js:7:94087)
    at http://hivevine.com/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor-26b0b943bef4e536710f.js:7:94252
    at http://hivevine.com/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor-26b0b943bef4e536710f.js:7:83865
    at Array.forEach (<anonymous>)
    at o (http://hivevine.com/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor-26b0b943bef4e536710f.js:7:83837)
    at http://hivevine.com/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor-26b0b943bef4e536710f.js:7:82254
    at Object.p [as dispatch] (http://hivevine.com/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor-26b0b943bef4e536710f.js:7:74694)
    at e (<anonymous>:2494:20)
    at http://hivevine.com/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor-26b0b943bef4e536710f.js:7:79875

Original stack trace:

    in SetupSuccessBannerNotification
    in BannerNotifications
    in div
    in Header
    in DashboardMainApp
    in DashboardEntryPoint
    in RestoreSnapshots
    in ErrorHandler
    in ThemeProvider
    in StrictMode
    in Root```

```
## Steps to reproduce

1. Enable TwG feature module.
2. St up Site Kit with analytics on Site without SSL.
3. See errors on dashboard.

## Screenshots

https://user-images.githubusercontent.com/94359491/194333281-d0406fb1-44bd-4e4c-8a8b-bf4d64b6c486.mp4

## Additional Context

 - Site without SSL.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

* 

```

**Comment by aaemnnosttv** [comment]
Closing in favor of #6134
