### ISSUE TITLE
Prevent incorrect container lookup when selecting a new Google Tag via the Google Tag ID Mismatch Notification banner.

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#6784]
## Feature Description

When choosing a new Google Tag via the Google Tag ID Mismatch Notification banner, an unnecessary request is made to the `GET:container-destinations` endpoint with the new `googleTagAccountID` but the old `googleTagContainerID`, resulting in a console error.

This does not appear to have any unwanted side effects, but should be prevented.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When choosing a new Google Tag via the Google Tag ID Mismatch Notification banner, the unnecessary request described above should not occur, and a console error should not be displayed.

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by tofumatt** [comment]
I like the easy approach; it's much easier to understand too!

This one's missing an estimate, but I'll go with a 7, largely just to handle the QA here as GTE QA can take a bit of set up time.

IB ✅

**Comment by mohitwp** [comment]
### QA Update ❌ 

@techanvil I followed the QAB of https://github.com/google/site-kit-wp/issues/6373 and tried to recreate the scenarios. 

- I've noticed that after clicking on button 1 [Use Property name (id)]. Property id and container id is changing, but tag is not changed also if we go to settings and click on 'edit in analytics' link then it is not navigating to actual connected property and under analytics settings edit mode empty property and web stream fields are showing. 
It was working fine before. You can verify it under video posted under [comment on 6373.](https://github.com/google/site-kit-wp/issues/6373#issuecomment-1493719758)

- Also, when I clicked on button [Use Property name (id)] it created fatal error. I tested this scenario 5 times and it happened only 1 time. 

```
`An error occurred while running 'mapSelect': Cannot assign to read only property '0' of object '[object Array]'
The error may be correlated with this previous error:
TypeError: Cannot assign to read only property '0' of object '[object Array]'
    at Array.sort (<anonymous>)
    at xe.getAnalyticsConfigByMeasurementIDs (https://ome-walrus-fego.instawp.xyz/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-modules-analytics-4-8ab47f1de6a70c925b7c.js:22:33791)
    at t (https://ome-walrus-fego.instawp.xyz/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor-57bb9005ccd4645ffcbf.js:7:75315)
    at https://ome-walrus-fego.instawp.xyz/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor-57bb9005ccd4645ffcbf.js:7:503255
    at Object.n [as getAnalyticsConfigByMeasurementIDs] (https://ome-walrus-fego.instawp.xyz/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor-57bb9005ccd4645ffcbf.js:7:502821)
    at Object.current (https://ome-walrus-fego.instawp.xyz/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-main-dashboard-9ee6eb3b729ecb3fa45a.js:80:9133)
    at e (https://ome-walrus-fego.instawp.xyz/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor-57bb9005ccd4645ffcbf.js:7:415212)
    at https://ome-walrus-fego.instawp.xyz/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor-57bb9005ccd4645ffcbf.js:7:415374
    at https://ome-walrus-fego.instawp.xyz/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor-57bb9005ccd4645ffcbf.js:7:507557
    at Array.forEach (<anonymous>)

Original stack trace:

    in GoogleTagIDMismatchNotification
    in BannerNotifications
    in div
    in Header
    in DashboardMainApp
    in DashboardEntryPoint
    in RestoreSnapshots
    in ErrorHandler
    in ThemeProvider
    in StrictMode
    in Root`
```

Please find related screencast below.


<details>


https://user-images.githubusercontent.com/94359491/230045994-1f9308e2-d2f3-40df-98b3-b2961c72acf7.mp4


https://user-images.githubusercontent.com/94359491/230047637-6bc48ab9-0c87-469a-bc32-be58bafd433b.mp4

</details>

**Comment by techanvil** [comment]
Hi @mohitwp, thanks for raising these issues.

Firstly, I need to clarify what should happen when pressing the "Use {property}" button. In this case, we are _not_ updating the Google tag settings. What's happening here is, Site Kit has identified that the current Google tag no longer points to the currently selected property, and it points to a different one. Pressing the "Use {property}" button tells Site Kit to continue using the same Google tag, but update the current property to be the one the tag now points to. So, the `measurementID`, `propertyID` and `webDataStreamID` settings should update, but the Google tag settings should not. The "Update Google tag" button is the opposite scenario - in this case, Site Kit has identified the new Google tag that points to the current property, and when pressing this button, the Google tag settings should be updated while `measurementID`, `propertyID` and `webDataStreamID` should remain the same.

Secondly - in my testing, the "Use {property}" button is still working as expected in the happy path. The behaviour you are describing with the dropdowns having empty labels looks like what happens when a property is selected with a different Analytics account to the current account, which has been captured in issue https://github.com/google/site-kit-wp/issues/6765.

To me, it doesn't seem like this issue has caused a regression. What I'd suggest is you run through this again, and be clear about the way you've chosen the new destinations for the Google tags - are they for properties in the same Analytics account?

If so, then it might be worth adding a comment with your findings to https://github.com/google/site-kit-wp/issues/6765 to make sure they are captured for a retest on that issue.

Furthermore, please ensure you do retest here with properties which _are_ in the same account. If you run into more issues, drop me a line and we can take a look together.

**Comment by mohitwp** [comment]
### QA Update ✅ 

Thank you @techanvil !

- Tested on main environment.
- Tested scenario for both CTA of banner A.
- I followed the QAB of https://github.com/google/site-kit-wp/issues/6373 and tried to recreate the scenarios.
- I rerun the scenarios for button 'Update Property name id' button and now I'm empty property fields are not showing under analytics settings mode.
- Although, I created new site and clicking on 'Update Property name id' generated error as mentioned [above in 2nd point](https://github.com/google/site-kit-wp/issues/6784#issuecomment-1497231339) so I created separated ticket for this #6843.
- Verified JS console errors are not appearing.

<details>


https://user-images.githubusercontent.com/94359491/230890195-1ea154bf-4ea0-423b-8b68-2ecfdb968905.mp4

</details>
