### ISSUE TITLE
`An error occurred while running 'mapSelect': Cannot read properties of null (reading 'isGA4DashboardView') The error may be correlated with this previous error:

### ISSUE THREAD

**Issue by networth1212** [google/site-kit-wp#7404]
`An error occurred while running 'mapSelect': Cannot read properties of null (reading 'isGA4DashboardView')
The error may be correlated with this previous error:
TypeError: Cannot read properties of null (reading 'isGA4DashboardView')
    at x.getViewableModules (https://highnetworths.info/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-datastore-user-391f5fdc6b158693b82d.js:3:21870)
    at t (https://highnetworths.info/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor-d5b0fdb2afc588c8ec4a.js:7:35002)
    at https://highnetworths.info/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor-d5b0fdb2afc588c8ec4a.js:7:474945
    at Object.n [as getViewableModules] (https://highnetworths.info/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor-d5b0fdb2afc588c8ec4a.js:7:474511)
    at Object.current (https://highnetworths.info/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-splash-a7f2faecfac6abfd5376.js:32:7483)
    at e (https://highnetworths.info/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor-d5b0fdb2afc588c8ec4a.js:7:331568)
    at https://highnetworths.info/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor-d5b0fdb2afc588c8ec4a.js:7:331675
    at Ii (https://highnetworths.info/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor-d5b0fdb2afc588c8ec4a.js:7:711315)
    at Ji (https://highnetworths.info/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor-d5b0fdb2afc588c8ec4a.js:7:711418)
    at Sj (https://highnetworths.info/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor-d5b0fdb2afc588c8ec4a.js:7:729362)

Original stack trace:

    in SetupUsingProxyWithSignIn
    in DashboardSplashApp
    in RestoreSnapshots
    in ErrorHandler
    in ThemeProvider
    in StrictMode
    in Root`

**Comment by jamesozzie** [comment]
Thanks for opening a GitHub issue @networth1212. So we can determine more on this please [open a support topic](https://wordpress.org/support/plugin/google-site-kit/#new-post) over on the plugins WordPress support forums, where we provide initial support assistance. We also have a [GitHub issue open](https://github.com/google/site-kit-wp/issues/7009) in relation to this (https://github.com/google/site-kit-wp/issues/7009) so any further details we can determine may be useful for others who may encounter the same. 

When opening a support topic please include all relevant details in order for us to assist. This may include [sharing your Site Health information](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/), referencing your support topic. 

I'll close this GitHub issue, and keep an eye out for your topic. Thank you.
