### ISSUE TITLE
Console Error when Custom Dimensions Metrics Selected While Analytics is Disconnected

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#7781]
## Bug Description

This is a bit of an edge case but I found a console error in a specific scenario. 

On the KMW you have the `Top performing keywords` tile selected (Search Console) and 1 or 2 Analytics tiles.  You therefore have one or two empty tile slots in the widget. Then, Analytics is disconnected, so what appears is the one search console tile and the CTA to connect Analytics in the 1 or 2 Analytics tiles you selected. 

The user then clicks on the 'Add a Metric' tile and then select one with a custom dimension, i.e. `Most popular authors by pageviews` and they go through the oAuth process. When this is completed they are sent back to the dashboard and everything looks fine in that the CTA to connect Analytics increases to take the additional tile selected. 

In Console though an error appears:

```
`Uncaught (in promise) Invariant Violation: A valid GA4 propertyID is required.`
    at e.exports (https://arisesand.s1-tastewp.com/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor-4c16654c8e7f27e5ee20.js:1:2501)
    at validateParams (https://arisesand.s1-tastewp.com/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-modules-analytics-4-179df0d36304607a94c1.js:1:17058)
    at Object.fetchCreateCustomDimension (https://arisesand.s1-tastewp.com/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-datastore-site-bb939be5f0018bb38096.js:1:38091)
    at https://arisesand.s1-tastewp.com/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-modules-analytics-4-179df0d36304607a94c1.js:1:18631
    at u (https://arisesand.s1-tastewp.com/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor-4c16654c8e7f27e5ee20.js:7:619274)
    at Generator._invoke (https://arisesand.s1-tastewp.com/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor-4c16654c8e7f27e5ee20.js:7:619027)
    at forEach.e.<computed> [as next] (https://arisesand.s1-tastewp.com/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor-4c16654c8e7f27e5ee20.js:7:619713)
    at https://arisesand.s1-tastewp.com/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor-4c16654c8e7f27e5ee20.js:7:763566
    at t.any (https://arisesand.s1-tastewp.com/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor-4c16654c8e7f27e5ee20.js:7:764199)
    at https://arisesand.s1-tastewp.com/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor-4c16654c8e7f27e5ee20.js:7:763678
```

You can see the issue in action here: 

https://github.com/google/site-kit-wp/assets/73545194/84387232-9f55-4dff-87f9-22592bc7a36f

## Steps to reproduce

See detail above. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

- The custom dimensions creation flow should not be initiated if the Analytics module is not connected, i.e.
  - The user should not be directed to the OAuth flow to grant the necessary authentication scope.
  - The request to create custom dimensions should not be made.

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
Closing in favor of https://github.com/google/site-kit-wp/issues/7754 which will also address this
